---
dependencies: []
galaxy_info:
  description: Install EPEL repository on RHEL based distributions
  platforms:
    - name: Amazon
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags: []
