---
dependencies: []
galaxy_info:
  description: "Manage users and groups"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags: []
