- name: this is timesync role for {{ inventory_name }}
  hosts: all

  become: true
  remote_user: remote

  var: 
    timesync_ntp_servers:
        - hostname: 3.kr.pool.ntp.org
          iburst: true
    roles:
      - linux-system-roles.timesync
