---
# handlers file for adguard role
- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved.service
    state: restarted
  listen: restart_resolved

- name: Restart AdGuard Home service
  ansible.builtin.service:
    name: AdGuardHome.service
    state: restarted
  listen: restart_adguardhome
