---
# tasks file for users role
- name: Manage groups
  ansible.builtin.group:
    name: '{{ group.name | default(group) }}'
    gid: '{{ group.gid | default(omit) }}'
    local: '{{ group.local | default(omit) }}'
    non_unique: '{{ group.non_unique | default(omit) }}'
    state: '{{ group.state | default(omit) }}'
    system: '{{ group.system | default(omit) }}'
  loop: '{{ managed_groups }}'
  loop_control:
    label: '{{ group.name | default(group) }}'
    loop_var: group

- name: Manage users
  ansible.builtin.user:
    name: '{{ user.name | default(user) }}'
    append: '{{ user.append | default(omit) }}'
    authorization: '{{ user.authorization | default(omit) }}'
    comment: '{{ user.comment | default(omit) }}'
    create_home: '{{ user.create_home | default(omit) }}'
    expires: '{{ user.expires | default(omit) }}'
    force: '{{ user.force | default(omit) }}'
    generate_ssh_key: '{{ user.generate_ssh_key | default(omit) }}'
    group: '{{ user.group | default(omit) }}'
    groups: '{{ user.groups | default(omit) }}'
    hidden: '{{ user.hidden | default(omit) }}'
    home: '{{ user.home | default(omit) }}'
    local: '{{ user.local | default(omit) }}'
    login_class: '{{ user.login_class | default(omit) }}'
    move_home: '{{ user.move_home | default(omit) }}'
    non_unique: '{{ user.non_unique | default(omit) }}'
    password: '{{ user.password | default(omit) }}'
    password_lock: '{{ user.password_lock | default(omit) }}'
    profile: '{{ user.profile | default(omit) }}'
    remove: '{{ user.remove | default(omit) }}'
    role: '{{ user.role | default(omit) }}'
    seuser: '{{ user.seuser | default(omit) }}'
    shell: '{{ user.shell | default(omit) }}'
    skeleton: '{{ user.skeleton | default(omit) }}'
    ssh_key_bits: '{{ user.ssh_key_bits | default(omit) }}'
    ssh_key_comment: '{{ user.ssh_key_comment | default(omit) }}'
    ssh_key_file: '{{ user.ssh_key_file | default(omit) }}'
    ssh_key_passphrase: '{{ user.ssh_key_passphrase | default(omit) }}'
    ssh_key_type: '{{ user.ssh_key_type | default(omit) }}'
    state: '{{ user.state | default(omit) }}'
    system: '{{ user.system | default(omit) }}'
    uid: '{{ user.uid | default(omit) }}'
    update_password: '{{ user.update_password | default(omit) }}'
  loop: '{{ managed_users }}'
  loop_control:
    label: '{{ user.name | default(user) }}'
    loop_var: user
