---
# tasks file for adguardhome role
- name: Check required variables
  ansible.builtin.import_tasks: assert.yml
  tags: adguard, assert, always

- name: Provide possibility to run on all interfaces
  ansible.builtin.import_tasks: preinstall.yml
  when: adguardhome_listen_all
  tags: adguard, adguard-preinstall

- name: Flush handlers to restart systemd-resolved
  meta: flush_handlers

- name: Run {{ adguardhome_install_method }} install method tasks
  ansible.builtin.include_tasks:
    file: "install_{{ adguardhome_install_method }}.yml"
    apply:
      tags: adguard, adguard-install
  tags: adguard, adguard-install
