---
- name: Populate service facts
  ansible.builtin.service_facts:

- when:
    - ansible_service_mgr == 'systemd'
    - ansible_facts.services['systemd-resolved.service'] is defined
    - ansible_facts.services['systemd-resolved.service'].status == 'enabled'
  block:
    - name: Create resolved drop-in directory
      ansible.builtin.file:
        path: /etc/systemd/resolved.conf.d
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Apply systemd-resolved config file
      ansible.builtin.copy:
        src: adguardhome.conf
        dest: /etc/systemd/resolved.conf.d/adguardhome.conf
        owner: root
        group: root
        mode: 0644
      notify: restart_resolved

    - name: Update /etc/resolv.conf symlink
      ansible.builtin.file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link
