---
dependencies: []

galaxy_info:
  description: 'Deploy traefik v2 with TLS support'
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags: []
