---
- name: Ensure traefik docker network state
  community.docker.docker_network:
    name: '{{ traefik_docker_network }}'
    state: present

- name: Launch traefik container
  community.docker.docker_container:
    name: traefik
    image: 'traefik:{{ traefik_version }}'
    command_handling: correct
    command: ['--configfile={{ traefik_configfile_static }}']
    comparisons: {'*': strict}
    env: '{{ traefik_env }}'
    network_mode: '{{ traefik_docker_network }}'
    published_ports: '{{ traefik_published_ports | select | list }}'
    pull: true
    recreate: false
    restart_policy: unless-stopped
    restart: '{{ _traefik_config.changed | default(false) }}'
    security_opts: ['no-new-privileges:true']
    state: started
    volumes: '{{ traefik_mount_volumes | select | list }}'
  vars:
    traefik_mount_volumes:
      - '{{ traefik_home }}:{{ traefik_home }}'
      - '{{ "/var/run/docker.sock:/var/run/docker.sock:ro" if not traefik_provider_docker_endpoint }}'
    traefik_published_ports:
      - '{{ "80:80" if not (traefik_disable_http and traefik_enable_https) }}'
      - '{{ "443:443" if traefik_enable_https }}'
